USE [WGCACAK]
GO

INSERT INTO [dbo].[realtime]
           ([LT_PV_Kg_LT_101H]
           ,[LT_PV_Kg_LT_101N]
           ,[LT_PV_Kg_LT_102H]
           ,[LT_PV_Kg_LT_102N]
           ,[LT_PV_Kg_LT_301H]
           ,[LT_PV_Kg_LT_301N]
           ,[LT_PV_Kg_LT_401H]
           ,[LT_PV_Kg_LT_401N]
           ,[LT_PV_m3_LT_101H]
           ,[LT_PV_m3_LT_101N]
           ,[LT_PV_m3_LT_102H]
           ,[LT_PV_m3_LT_102N]
           ,[LT_PV_m3_LT_301H]
           ,[LT_PV_m3_LT_301N]
           ,[LT_PV_m3_LT_401H]
           ,[LT_PV_m3_LT_401N]
           ,[AAA_LT_101H_Output]
           ,[AAA_LT_101N_Output]
           ,[AAA_LT_102H_Output]
           ,[AAA_LT_102N_Output]
           ,[AAA_LT_301H_Output]
           ,[AAA_LT_301N_Output]
           ,[AAA_LT_401H_Output]
           ,[AAA_LT_401N_Output]
           ,[Auto_Mode_H]
           ,[Auto_Mode_N]
           ,[PB_Start_Auto_H]
           ,[PB_Start_Auto_N]
           ,[PB_Stop_Auto_H]
           ,[PB_Stop_Auto_N]
           ,[AAA_PU_401N_Run]
           ,[AAA_PU_401H_Run]
           ,[AAA_PU_402N_Run]
           ,[AAA_PU_402H_Run]
           ,[AAA_PU_403N_Run]
           ,[AAA_PU_403H_Run]
           ,[DI_AKA_PD01]
           ,[DI_AKA_PD02]
           ,[DI_AKA_PD03]
           ,[DI_ACID_PD01]
           ,[DI_ACID_PD02]
           ,[DI_ACID_PD03]
           ,[Tranfer_SP_Total_PD1_H]
           ,[Tranfer_SP_Total_PD1_N]
           ,[Tranfer_SP_Total_PD2_H]
           ,[Tranfer_SP_Total_PD2_N]
           ,[Tranfer_SP_Total_PD3_H]
           ,[Tranfer_SP_Total_PD3_N]
           ,[AAA_FT_401H_Total]
           ,[AAA_FT_401N_Total]
           ,[AAA_FT_402H_Total]
           ,[AAA_FT_402N_Total]
           ,[AAA_FT_403H_Total]
           ,[AAA_FT_403N_Total]
           ,[Rcipe_H_1]
           ,[Rcipe_N_1]
           ,[ACID_Timer_PD01_PV]
           ,[ACID_Timer_PD01_SP]
           ,[ACID_Timer_PD02_PV]
           ,[ACID_Timer_PD02_SP]
           ,[ACID_Timer_PD03_PV]
           ,[ACID_Timer_PD03_SP]
           ,[AKA_Timer_PD01_PV]
           ,[AKA_Timer_PD01_SP]
           ,[AKA_Timer_PD02_PV]
           ,[AKA_Timer_PD02_SP]
           ,[AKA_Timer_PD03_PV]
           ,[AKA_Timer_PD03_SP])
     VALUES
           (
            0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0
            ,0

           )
GO


